### ISSUE TITLE
'ImageDraw' object has no attribute 'textsize'

### ISSUE THREAD

**Issue by pscd-354** [akornatskyy/wheezy.captcha#40]

**Comment by pscd-354** [comment]
https://github.com/python-pillow/Pillow/commit/b2301d70d104f36a08ae658f569d02f7796fc8fa

**Comment by akornatskyy** [comment]
what do they advise to use instead?

**Comment by pacssee** [comment]
This makes wheezy incompatible with Pillow >=10. When will it be merged ?

**Comment by akornatskyy** [comment]
the PR seems to be incompatible with previous version of pillow (<10)... would be nice to confirm that first.

**Comment by leonelcamara** [comment]
For now I've simply monkeypatched pillow's ImageDraw in my code to make wheezy.captcha work, might be useful for others, just put this code before calling wheezy.captcha image functions:
```python
from PIL.ImageDraw import ImageDraw
def textsize(self, text, font=None):
    (left, top, right, bottom) = self.textbbox((0,0), text, font)
    return (abs(left - right), abs(top - bottom)*2)
ImageDraw.textsize = textsize
```

**Comment by bo-kwok** [comment]
> the PR seems to be incompatible with previous version of pillow (<10)... would be nice to confirm that first.

I apologize for not seeing your feedback earlier. I have now made the necessary corrections based on your suggestions. Please review it again and let me know if there are any further improvements needed.
Thanks
@akornatskyy

**Comment by hettmett** [comment]
@akornatskyy do you think you can merge @bo-kwok pull request or is there anything else need to be done?

**Comment by akornatskyy** [comment]
@hettmett : I have reviewed the PR, I used a slightly different [approach](https://github.com/akornatskyy/wheezy.captcha/commit/8e8fec459babd69a9edfe766e1ca16c9b675733f) with one time compatibility check. consider to check with version `3.2.1`, please.
